import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { MapPin, Calendar, Users, Plane, Train, Car, Utensils, Camera, Beer, Compass } from "lucide-react"

export default function TravelPlanDisplay() {
  // This would typically come from your API or state management
  const travelPlan = {
    fromLocation: "New York",
    toLocation: "Paris",
    numMembers: 2,
    travelType: "Air",
    travelGroupType: "Couple",
    numDays: 7,
    interests: ["Must See Attractions", "Great Food", "Hidden Gems", "Wine & Beer"],
    itinerary: [
      {
        day: 1,
        activities: [
          "Arrive in Paris",
          "Check-in to hotel",
          "Evening stroll along the Seine River",
          "Dinner at a local bistro"
        ]
      },
      {
        day: 2,
        activities: [
          "Visit the Eiffel Tower",
          "Lunch at a café in Montmartre",
          "Explore Sacré-Cœur Basilica",
          "Wine tasting experience"
        ]
      },
      // ... more days would be added here
    ]
  }

  const getIcon = (interest: string) => {
    switch (interest) {
      case "Must See Attractions":
        return <Camera className="h-4 w-4" />
      case "Great Food":
        return <Utensils className="h-4 w-4" />
      case "Hidden Gems":
        return <Compass className="h-4 w-4" />
      case "Wine & Beer":
        return <Beer className="h-4 w-4" />
      default:
        return null
    }
  }

  const getTravelIcon = (travelType: string) => {
    switch (travelType) {
      case "Air":
        return <Plane className="h-5 w-5" />
      case "Train":
        return <Train className="h-5 w-5" />
      case "Road":
        return <Car className="h-5 w-5" />
      default:
        return null
    }
  }

  return (
    <div className="container mx-auto py-10">
      <Card className="w-full max-w-4xl mx-auto">
        <CardHeader>
          <CardTitle className="text-3xl font-bold text-center">Your Travel Plan</CardTitle>
          <CardDescription className="text-center">Generated by AI Travel Planner</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div className="flex items-center space-x-2">
              <MapPin className="h-5 w-5 text-muted-foreground" />
              <span className="font-semibold">From:</span> {travelPlan.fromLocation}
            </div>
            <div className="flex items-center space-x-2">
              <MapPin className="h-5 w-5 text-muted-foreground" />
              <span className="font-semibold">To:</span> {travelPlan.toLocation}
            </div>
            <div className="flex items-center space-x-2">
              <Users className="h-5 w-5 text-muted-foreground" />
              <span className="font-semibold">Group:</span> {travelPlan.numMembers} {travelPlan.travelGroupType}
            </div>
            <div className="flex items-center space-x-2">
              {getTravelIcon(travelPlan.travelType)}
              <span className="font-semibold">Travel by:</span> {travelPlan.travelType}
            </div>
            <div className="flex items-center space-x-2">
              <Calendar className="h-5 w-5 text-muted-foreground" />
              <span className="font-semibold">Duration:</span> {travelPlan.numDays} days
            </div>
          </div>
          <div className="mb-6">
            <h3 className="text-lg font-semibold mb-2">Interests:</h3>
            <div className="flex flex-wrap gap-2">
              {travelPlan.interests.map((interest, index) => (
                <div key={index} className="flex items-center space-x-1 bg-secondary text-secondary-foreground rounded-full px-3 py-1 text-sm">
                  {getIcon(interest)}
                  <span>{interest}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h3 className="text-lg font-semibold mb-2">Itinerary:</h3>
            <ScrollArea className="h-[400px] w-full rounded-md border p-4">
              {travelPlan.itinerary.map((day, index) => (
                <div key={index} className="mb-4 last:mb-0">
                  <h4 className="font-semibold">Day {day.day}</h4>
                  <ul className="list-disc list-inside pl-4">
                    {day.activities.map((activity, actIndex) => (
                      <li key={actIndex} className="text-sm text-muted-foreground">{activity}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </ScrollArea>
          </div>
        </CardContent>
        <CardFooter className="flex justify-center space-x-4">
          <Button variant="outline">Edit Plan</Button>
          <Button>Save Plan</Button>
        </CardFooter>
      </Card>
    </div>
  )
}